---
- include_tasks: _common.yml
  tags: ['prometheus_mysqld_exporter']

- name: 'mysqld exporter | configuration'
  template:
    src: conf/prometheus-mysqld-exporter.j2
    dest: /etc/default/prometheus-mysqld-exporter
    owner: root
    group: root
    mode: 0600
  when:
    - prometheus_mysqld_exporter_user is defined
  register: prometheus_mysqld_exporter_configuration
  notify:
    - 'prometheus | mysqld exporter | restart service'
  tags: ['prometheus_mysqld_exporter']
