---
- include_tasks: _common.yml
  tags: ['prometheus_redis_exporter']

- name: 'redis exporter | configuration'
  template:
    src: conf/prometheus-redis-exporter.j2
    dest: /etc/default/prometheus-redis-exporter
    owner: root
    group: root
    mode: 0600
  register: prometheus_redis_exporter_configuration
  notify:
    - 'redis-exporter-restart'
  tags: ['prometheus_redis_exporter']
