---
- name: '{{ exporter }} exporter | download from repo'
  get_url:
    url: "{{prometheus_exporters_repo}}/releases/download/{{prometheus_exporters_release}}/{{exporter}}_exporter"
    dest: /usr/local/bin/prometheus-{{ exporter }}-exporter
    remote_src: yes
    owner: root
    group: root
    mode: 0755
  ignore_errors: '{{ ansible_check_mode }}'
  tags: [ 'prometheus_{{ exporter }}' ]
