---
- name: 'include asserts'
  include_tasks: 'asserts.yml'

- name: 'requirements'
  include_tasks: 'requirements.yml'

## prometheus server install
- name: 'server install'
  include_tasks: server/grafana-prometheus.yml
  include_tasks: server/grafana-provisioning.yml
  when:
    - prometheus_server_enable == "true"
  tags:
    - prometheus
    - prometheus_server
    - grafana
    - grafana_server
    - grafana_prometheus

## include exporter install
- name: 'exporters install'
  vars:
    exporter: "{{ item }}"
  include_tasks: "exporter/{{ item }}.yml"
  tags:
    - prometheus_node_exporter
    - prometheus_mysqld_exporter
    - prometheus_postgresql_exporter
    - prometheus_mongodb_exporter
    - prometheus_apache_exporter
    - prometheus_haproxy_exporter
    - prometheus_varnish_exporter
    - prometheus_redis_exporter
    - prometheus_memcached_exporter
    - prometheus_phpfpm_exporter
    - prometheus_opcache_exporter
    - prometheus_blackbox_exporter
    - prometheus_kong_exporter
  with_items:
    - "{{ prometheus_exporter_packages }}"
