---
- name: 'prometheus | include asserts'
  include_tasks: 'asserts.yml'

- name: 'prometheus | requirements'
  include_tasks: 'requirements.yml'

- name: 'prometheus | server install'
  include_tasks: 'prometheus.yml'
  when:
    - prometheus_server_enable == "true"

- name: 'prometheus | Node exporter'
  include_tasks: 'node_exporter.yml'
  when:
    - "'node' in prometheus_exporter_packages"

- name: 'prometheus | MongoDB exporter'
  include_tasks: 'mongodb_exporter.yml'
  when:
    - "'mongodb' in prometheus_exporter_packages"

- name: 'prometheus | MySQL exporter'
  include_tasks: 'mysqld_exporter.yml'
  when:
    - "'mysqld' in prometheus_exporter_packages"

- name: 'prometheus | PostgreSQL exporter'
  include_tasks: 'postgresql_exporter.yml'
  when:
    - "'postgresql' in prometheus_exporter_packages"

- name: 'prometheus | PHP Fpm exporter'
  include_tasks: 'phpfpm_exporter.yml'
  when:
    - "'phpfpm' in prometheus_exporter_packages"

- name: 'prometheus | PHP opcache exporter'
  include_tasks: 'opcache_exporter.yml'
  when:
    - "'opcache' in prometheus_exporter_packages"

- name: 'prometheus | Apache exporter'
  include_tasks: 'apache_exporter.yml'
  when:
    - "'apache' in prometheus_exporter_packages"

- name: 'prometheus | Varnish exporter'
  include_tasks: 'varnish_exporter.yml'
  when:
    - "'varnish' in prometheus_exporter_packages"

- name: 'prometheus | Blackbox exporter'
  include_tasks: 'blackbox_exporter.yml'
  when:
    - "'blackbox' in prometheus_exporter_packages"

- name: 'prometheus | Redis exporter'
  include_tasks: 'redis_exporter.yml'
  when:
    - "'redis' in prometheus_exporter_packages"

- name: 'prometheus | Memcached exporter'
  include_tasks: 'memcached_exporter.yml'
  when:
    - "'memcached' in prometheus_exporter_packages"
