---
- name: 'requirement | update APT Cache'
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: 'requirement | pre-requirements install'
  apt:
    name:
      - curl
      - jq
    state: present
  tags: ['prometheus']
