{
 "title": "CloudFlare Zone Analytics",
 "tags": [ "cloudflare" ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "zone",
    "label": "Zone",
    "query": {
     "query": "label_values(cloudflare_zone_requests_total, zone)"
    }
   },
   {
    "name": "regions",
    "label": "Regions",
    "query": {
     "query": "label_values(cloudflare_zone_requests_country, region)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(cloudflare_zone_requests_total{zone=~\"$zone\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Total Bandwidth",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(cloudflare_zone_bandwidth_total{zone=~\"$zone\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Requests / second",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(cloudflare_zone_requests_total{zone=~\"$zone\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Bandwidth / second",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(cloudflare_zone_bandwidth_total{zone=~\"$zone\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Total Unique Visitors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(cloudflare_zone_uniques_total{zone=~\"$zone\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Uniques / second",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(cloudflare_zone_uniques_total{zone=~\"$zone\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "Unique Visitors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(cloudflare_zone_uniques_total{zone=~\"$zone\"}[$__interval]))",
     "legendFormat": "visitors"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Requests / second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(cloudflare_zone_requests_total{zone=~\"$zone\"}[$__interval]))",
     "legendFormat": "total"
    },
    {
     "expr": "sum(rate(cloudflare_zone_requests_cached{zone=~\"$zone\"}[$__interval]))",
     "legendFormat": "cached"
    }
   ]
  },
  {
   "title": "Requests per Country / Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(cloudflare_zone_requests_country{zone=~\"$zone\"}[$__interval]) > 0) by (country)",
     "legendFormat": "{{country}}"
    }
   ]
  },
  {
   "title": "Requests / Second (status codes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(cloudflare_zone_requests_status{zone=~\"$zone\", status!~\"5..\"}[$__interval])) by (status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests / Second (status codes not 2XX)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(cloudflare_zone_requests_status{zone=~\"$zone\", status!~\"2..\"}[$__interval])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Errors / Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(cloudflare_zone_requests_status{zone=~\"$zone\", status=~\"5..\"}[$__interval])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Requests SSL",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(cloudflare_zone_requests_ssl_encrypted{zone=~\"$zone\"} / cloudflare_zone_requests_total{zone=~\"$zone\"})",
     "legendFormat": "encrypted"
    },
    {
     "expr": "avg((cloudflare_zone_requests_total{zone=~\"$zone\"} - cloudflare_zone_requests_ssl_encrypted{zone=~\"$zone\"}) / cloudflare_zone_requests_total{zone=~\"$zone\"})",
     "legendFormat": "unencrypted"
    }
   ]
  },
  {
   "title": "Cached Requests",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(cloudflare_zone_requests_cached{zone=~\"$zone\"} / cloudflare_zone_requests_total{zone=~\"$zone\"})",
     "legendFormat": "cached"
    },
    {
     "expr": "avg((cloudflare_zone_requests_total{zone=~\"$zone\"} - cloudflare_zone_requests_cached{zone=~\"$zone\"}) / cloudflare_zone_requests_total{zone=~\"$zone\"})",
     "legendFormat": "uncached"
    }
   ]
  },
  {
   "title": "Requests Status Codes",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(cloudflare_zone_requests_status{zone=~\"$zone\"}[$__range])",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Request Content Type",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(cloudflare_zone_requests_content_type{zone=~\"$zone\"}[$__range])",
     "legendFormat": "{{content_type}}"
    }
   ]
  },
  {
   "title": "Request Country",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(cloudflare_zone_requests_country{zone=~\"$zone\"}[$__range])",
     "legendFormat": "{{country}}"
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Bandwidth / second",
     "type": "graph",
     "gridPos": { "h": 10, "w": 23, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "rate(cloudflare_zone_bandwidth_total{zone=~\"$zone\"}[$__interval])",
       "legendFormat": "total"
      },
      {
       "expr": "rate(cloudflare_zone_bandwidth_cached{zone=~\"$zone\"}[$__interval])",
       "legendFormat": "cached"
      }
     ]
    },
    {
     "title": "Cached Bandwidth",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 26 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "cloudflare_zone_bandwidth_cached{zone=~\"$zone\"} / cloudflare_zone_bandwidth_total{zone=~\"$zone\"}",
       "legendFormat": "cached"
      },
      {
       "expr": "(cloudflare_zone_bandwidth_total{zone=~\"$zone\"} - cloudflare_zone_bandwidth_cached{zone=~\"$zone\"}) / cloudflare_zone_bandwidth_total{zone=~\"$zone\"}",
       "legendFormat": "uncached"
      }
     ]
    },
    {
     "title": "Bandwidth Content Type",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 10, "w": 11, "x": 12, "y": 26 },
     "format": "decbytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "rate(cloudflare_zone_bandwidth_content_type{zone=~\"$zone\"}[5m])",
       "legendFormat": "{{content_type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Regions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Requests by Region / second",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (region)(rate(cloudflare_zone_requests_country{zone=~\"$zone\"}[$__interval]))",
       "legendFormat": "{{ region }}"
      }
     ]
    },
    {
     "title": "Bandwidth by Region / second",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum by (region)(rate(cloudflare_zone_bandwidth_country{zone=~\"$zone\"}[$__interval]))",
       "legendFormat": "{{ region }}"
      }
     ]
    },
    {
     "title": "Requests in $regions / second",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 34 },
     "repeat": "regions",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(cloudflare_zone_requests_country{zone=~\"$zone\", region=~\"$regions\"}[$__interval]) > 10",
       "legendFormat": "{{ country }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Threats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Threats / second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(cloudflare_zone_threats_total{zone=~\"$zone\"}[1m])",
       "legendFormat": "{{zone}}/threats"
      }
     ]
    },
    {
     "title": "Threats / country",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(cloudflare_zone_threats_country{zone=~\"$zone\"}[1m])",
       "legendFormat": "{{country}}/threats"
      }
     ]
    },
    {
     "title": "Threats / type",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 70 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(cloudflare_zone_threats_type{zone=~\"$zone\"}[1m])",
       "legendFormat": "{{type}}/threats"
      }
     ]
    }
   ]
  },
  {
   "title": "Colocations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Visits  by Colocations / second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 74 },
     "repeat": "zone",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(cloudflare_zone_colocation_visits{zone=\"$zone\"}[$__interval]) > 0",
       "legendFormat": "{{ colocation }}"
      }
     ]
    }
   ]
  }
 ]
}