{
 "title": "HAProxy",
 "description": "HAProxy with Prometheus data",
 "tags": [ "haproxy" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(haproxy_process_nbproc,instance)"
    }
   },
   {
    "name": "backend",
    "label": "Backend",
    "query": {
     "query": "label_values(haproxy_backend_status{instance=~\"$host\"}, proxy)"
    }
   },
   {
    "name": "frontend",
    "label": "Frontend",
    "query": {
     "query": "label_values(haproxy_frontend_status{instance=~\"$host\"}, proxy)"
    }
   },
   {
    "name": "server",
    "label": "Server",
    "query": {
     "query": "label_values(haproxy_server_status{instance=~\"$host\"}, server)"
    }
   },
   {
    "name": "code",
    "label": "HTTP Code",
    "query": {
     "query": "label_values(haproxy_server_http_responses_total{instance=~\"$host\"}, code)"
    }
   },
   { "name": "interval", "label": "Interval", "query": "30s,1m,5m,1h,6h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Basic General Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Frontend Trafic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(instance)(rate(haproxy_frontend_http_responses_total{proxy=~\"$frontend\",code=~\"$code\",instance=~\"$host\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Frontend HTTP responses",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(haproxy_frontend_http_responses_total{proxy=~\"$frontend\",code=~\"$code\",instance=~\"$host\"}[$__rate_interval])) by (code)",
     "legendFormat": "Front {{ code }}"
    }
   ]
  },
  {
   "title": "Backend HTTP responses",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(haproxy_backend_http_responses_total{proxy=~\"$backend\",code=~\"$code\",instance=~\"$host\"}[$__rate_interval])) by (code)",
     "legendFormat": "Back {{ code }}"
    }
   ]
  },
  {
   "title": "Incoming / Outgoing bytes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "expr": "sum(rate(haproxy_frontend_bytes_in_total{proxy=~\"$frontend\",instance=~\"$host\"}[$__rate_interval])*8)",
     "legendFormat": "IN Front"
    },
    {
     "expr": "sum(rate(haproxy_frontend_bytes_out_total{proxy=~\"$frontend\",instance=~\"$host\"}[$__rate_interval])*8)",
     "legendFormat": "OUT Front"
    },
    {
     "expr": "sum(rate(haproxy_backend_bytes_in_total{proxy=~\"$backend\",instance=~\"$host\"}[$__rate_interval])*8)",
     "legendFormat": "IN Back"
    },
    {
     "expr": "sum(rate(haproxy_backend_bytes_out_total{proxy=~\"$backend\",instance=~\"$host\"}[$__rate_interval])*8)",
     "legendFormat": "OUT Back"
    }
   ]
  },
  {
   "title": "Number of connections",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(haproxy_frontend_connections_total{proxy=~\"$frontend\",instance=~\"$host\"}[$__rate_interval]))",
     "legendFormat": "Front"
    },
    {
     "expr": "sum(rate(haproxy_backend_connection_errors_total{proxy=~\"$backend\",instance=~\"$host\"}[$__rate_interval]))",
     "legendFormat": "Back errors"
    }
   ]
  },
  {
   "title": "Requests and Responses",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(haproxy_frontend_http_requests_total{proxy=~\"$frontend\",instance=~\"$host\"}[$__rate_interval]))",
     "legendFormat": "Front requests"
    },
    {
     "expr": "sum(rate(haproxy_frontend_request_errors_total{proxy=~\"$frontend\",instance=~\"$host\"}[$__rate_interval]))",
     "legendFormat": "Front requests errors"
    },
    {
     "expr": "sum(rate(haproxy_frontend_requests_denied_total{proxy=~\"$frontend\",instance=~\"$host\"}[$__rate_interval]))",
     "legendFormat": "Front request denied"
    },
    {
     "expr": "sum(rate(haproxy_backend_redispatch_warnings_total{proxy=~\"$backend\",instance=~\"$host\"}[$__rate_interval]))",
     "legendFormat": "Back redispatch warnings"
    },
    {
     "expr": "sum(rate(haproxy_backend_retry_warnings_total{proxy=~\"$backend\",instance=~\"$host\"}[$__rate_interval]))",
     "legendFormat": "Back retry warnings"
    },
    {
     "expr": "sum(rate(haproxy_backend_response_errors_total{proxy=~\"$backend\",instance=~\"$host\"}[$__rate_interval]))",
     "legendFormat": "Back response errors"
    },
    {
     "expr": "sum(haproxy_backend_current_queue{proxy=~\"$backend\",instance=~\"$host\"})",
     "legendFormat": "Back queued requests"
    },
    {
     "expr": "sum(rate(haproxy_backend_http_requests_total{proxy=~\"$backend\",instance=~\"$host\"}[$__rate_interval]))",
     "legendFormat": "Back requests"
    }
   ]
  },
  {
   "title": "Active sessions",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(haproxy_frontend_current_sessions{proxy=~\"$frontend\",instance=~\"$host\"})",
     "legendFormat": "Front"
    }
   ]
  },
  {
   "title": "Basic General Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {}
   ]
  },
  {
   "title": "All Status",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 22, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(haproxy_frontend_status{instance=~\"$host\"} == 1)",
     "legendFormat": "Front Up"
    },
    {
     "expr": "count(haproxy_backend_status{instance=~\"$host\"} ==1)",
     "legendFormat": "Back Up"
    }
   ]
  },
  {
   "title": "Started...",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "min(time() - haproxy_process_start_time_seconds{instance=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Throughtput / Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Front - Incoming / Outgoing connections",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 12, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(haproxy_frontend_connections_total{proxy=~\"$frontend\",instance=~\"$host\"}[$__rate_interval])*8) by (proxy)",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Incoming / Outgoing connections",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 12, "x": 12, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(haproxy_backend_connection_attempts_total{proxy=~\"$backend\",instance=~\"$host\"}[$__rate_interval])*8) by (proxy)",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Front - Connections successful / denied",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 12, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(haproxy_frontend_connections_total{proxy=~\"$frontend\",instance=~\"$host\"}[$__rate_interval])) by (proxy)",
       "legendFormat": "Successful {{ proxy }}"
      },
      {
       "expr": "sum(rate(haproxy_frontend_denied_connections_total{proxy=~\"$frontend\",instance=~\"$host\"}[$__rate_interval])) by (proxy)",
       "legendFormat": "Denied {{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Connections attempts / errors",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 12, "x": 12, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(haproxy_backend_connection_attempts_total{proxy=~\"$backend\",instance=~\"$host\"}[$__rate_interval])) by (proxy)",
       "legendFormat": "Attempts {{ proxy }}"
      },
      {
       "expr": "sum(rate(haproxy_backend_connection_errors_total{proxy=~\"$backend\",instance=~\"$host\"}[$__rate_interval])) by (proxy)",
       "legendFormat": "Error {{ proxy }}"
      }
     ]
    },
    {
     "title": "Front - Maximum observed number of connections per second",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 12, "x": 0, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(haproxy_frontend_connections_rate_max{proxy=~\"$frontend\",instance=~\"$host\"}) by (proxy)",
       "legendFormat": "Max {{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Connections reuses",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 12, "x": 12, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(haproxy_backend_connection_reuses_total{proxy=~\"$backend\",instance=~\"$host\"}[$__rate_interval])) by (proxy)",
       "legendFormat": "Reuses {{ proxy }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Queues",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Back - Queued requests not assigned to any server",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(haproxy_backend_current_queue{proxy=~\"$backend\",instance=~\"$host\"}) by (proxy)",
       "legendFormat": "Queued {{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Max queued requests not assigned to any server",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(haproxy_backend_max_queue{proxy=~\"$backend\",instance=~\"$host\"}) by (proxy)",
       "legendFormat": "Max {{ proxy }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Requests / Responses",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Front - HTTP requests OK / Error / Denied",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(haproxy_frontend_http_requests_total{proxy=~\"$frontend\",instance=~\"$host\"}[$__rate_interval])) by (proxy)",
       "legendFormat": "Total {{ proxy }}"
      },
      {
       "expr": "sum(rate(haproxy_frontend_request_errors_total{proxy=~\"$frontend\", instance=~\"$host\"}[$__rate_interval])) by (proxy)",
       "legendFormat": "Error {{ proxy }}"
      },
      {
       "expr": "sum(rate(haproxy_frontend_requests_denied_total{proxy=~\"$frontend\", instance=~\"$host\"}[$__rate_interval])) by (proxy)",
       "legendFormat": "Denied {{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - HTTP responses denied",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(haproxy_backend_responses_denied_total{proxy=~\"$backend\", instance=~\"$host\"}[$__rate_interval])) by (proxy)",
       "legendFormat": "Denied {{ proxy }}"
      }
     ]
    },
    {
     "title": "Front - HTTP responses denied",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(haproxy_frontend_responses_denied_total{proxy=~\"$frontend\",instance=~\"$host\"}[$__rate_interval])) by (proxy)",
       "legendFormat": "Denied {{ proxy }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Times",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Back - Avg connection time",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(haproxy_backend_connect_time_average_seconds{proxy=~\"$backend\",instance=~\"$host\"}) by (proxy) != 0",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Max connection time",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(haproxy_backend_max_connect_time_seconds{proxy=~\"$backend\",instance=~\"$host\"}) by (proxy) != 0",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Avg. response time",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "haproxy_backend_response_time_average_seconds{proxy=~\"$backend\",instance=~\"$host\"} != 0",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Max response time",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(haproxy_backend_max_response_time_seconds{proxy=~\"$backend\",instance=~\"$host\"}) by (proxy) != 0",
       "legendFormat": "{{ proxy }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Front - Number of sessions",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(haproxy_frontend_sessions_total{proxy=~\"$frontend\",instance=~\"$host\"}[$__rate_interval])) by (proxy)",
       "legendFormat": "Total {{ proxy }}"
      },
      {
       "expr": "sum(rate(haproxy_frontend_denied_sessions_total{proxy=~\"$frontend\",instance=~\"$host\"}[$__rate_interval])) by (proxy)",
       "legendFormat": "Denied {{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Number of sessions",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(haproxy_backend_sessions_total{proxy=~\"$backend\",instance=~\"$host\"}[$__rate_interval])) by (proxy)",
       "legendFormat": "Total {{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Maximum observed number of active sessions and limit",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(haproxy_backend_max_sessions{proxy=~\"$backend\",instance=~\"$host\"}) by (proxy)",
       "legendFormat": "Max {{ proxy }}"
      },
      {
       "expr": "sum(haproxy_backend_limit_sessions{proxy=~\"$backend\",instance=~\"$host\"}) by (proxy)",
       "legendFormat": "Limit {{ proxy }}"
      }
     ]
    },
    {
     "title": "Front - Maximum observed number of active sessions and limit",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(haproxy_frontend_max_sessions{proxy=~\"$frontend\",instance=~\"$host\"}) by (proxy)",
       "legendFormat": "Max {{ proxy }}"
      },
      {
       "expr": "sum(haproxy_frontend_limit_sessions{proxy=~\"$frontend\",instance=~\"$host\"}) by (proxy)",
       "legendFormat": "Limit {{ proxy }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Health and Weight",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Back - UP->DOWN transitions",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(haproxy_backend_check_up_down_total{proxy=~\"$backend\", instance=~\"$host\"}[$__rate_interval])) by (proxy)",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Service weight",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(haproxy_backend_weight{proxy=~\"$backend\", instance=~\"$host\"}) by (proxy)",
       "legendFormat": "{{ proxy }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cache / Compressor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Front - Cache lookups / hits",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(haproxy_frontend_http_cache_lookups_total{proxy=~\"$backend\", instance=~\"$host\"}[$__rate_interval])) by (proxy)",
       "legendFormat": "Lookups {{ proxy }} "
      },
      {
       "expr": "sum(rate(haproxy_frontend_http_cache_hits_total{proxy=~\"$backend\", instance=~\"$host\"}[$__rate_interval])) by (proxy)",
       "legendFormat": "Hits {{ proxy }} "
      }
     ]
    },
    {
     "title": "Back - Cache lookups / hits",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(haproxy_backend_http_cache_lookups_total{proxy=~\"$backend\", instance=~\"$host\"}[$__rate_interval])) by (proxy)",
       "legendFormat": "Lookups {{ proxy }} "
      },
      {
       "expr": "sum(rate(haproxy_backend_http_cache_hits_total{proxy=~\"$backend\", instance=~\"$host\"}[$__rate_interval])) by (proxy)",
       "legendFormat": "Hits {{ proxy }} "
      }
     ]
    },
    {
     "title": "Front - Compressor",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(haproxy_frontend_http_comp_bytes_in_total{proxy=~\"$backend\", instance=~\"$host\"}[$__rate_interval])) by (proxy)",
       "legendFormat": "Bytes fed {{ proxy }} "
      },
      {
       "expr": "sum(rate(haproxy_frontend_http_comp_bytes_out_total{proxy=~\"$backend\", instance=~\"$host\"}[$__rate_interval])) by (proxy)",
       "legendFormat": "Bytes emitted {{ proxy }} "
      },
      {
       "expr": "sum(rate(haproxy_frontend_http_comp_bytes_bypassed_total{proxy=~\"$backend\", instance=~\"$host\"}[$__rate_interval])) by (proxy)",
       "legendFormat": "Bytes bypassed  {{ proxy }} "
      }
     ]
    },
    {
     "title": "Back - Compressor",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(haproxy_backend_http_comp_bytes_in_total{proxy=~\"$backend\", instance=~\"$host\"}[$__rate_interval])) by (proxy)",
       "legendFormat": "Bytes fed {{ proxy }} "
      },
      {
       "expr": "sum(rate(haproxy_backend_http_comp_bytes_out_total{proxy=~\"$backend\", instance=~\"$host\"}[$__rate_interval])) by (proxy)",
       "legendFormat": "Bytes emitted {{ proxy }} "
      },
      {
       "expr": "sum(rate(haproxy_backend_http_comp_bytes_bypassed_total{proxy=~\"$backend\", instance=~\"$host\"}[$__rate_interval])) by (proxy)",
       "legendFormat": "Bytes bypassed  {{ proxy }} "
      }
     ]
    },
    {
     "title": "Front - Responses compressed",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(haproxy_frontend_http_comp_responses_total{proxy=~\"$backend\", instance=~\"$host\"}[$__rate_interval])) by (proxy)",
       "legendFormat": "{{ proxy }} "
      }
     ]
    },
    {
     "title": "Back - Responses compressed",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(haproxy_backend_http_comp_responses_total{proxy=~\"$backend\", instance=~\"$host\"}[$__rate_interval])) by (proxy)",
       "legendFormat": "{{ proxy }} "
      }
     ]
    }
   ]
  },
  {
   "title": "Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Front - Status",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(haproxy_frontend_status{proxy=~\"$frontend\",instance=~\"$host\"}) by (proxy)",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Status",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(haproxy_backend_status{proxy=~\"$backend\",instance=~\"$host\"}) by (proxy)",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Front - Internal errors",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(haproxy_frontend_internal_errors_total{proxy=~\"$backend\",instance=~\"$host\"}[$__rate_interval])) by (proxy)",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Internal errors",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(haproxy_backend_internal_errors_total{proxy=~\"$backend\",instance=~\"$host\"}[$__rate_interval])) by (proxy)",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Active servers",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(haproxy_backend_active_servers{proxy=~\"$backend\",instance=~\"$host\"}) by (proxy)",
       "legendFormat": "{{ proxy }}"
      }
     ]
    },
    {
     "title": "Back - Backup servers",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(haproxy_backend_backup_servers{proxy=~\"$backend\",instance=~\"$host\"}) by (proxy)",
       "legendFormat": "{{ proxy }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Process Misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Process - Memory",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(haproxy_process_max_memory_bytes{instance=~\"$host\"})",
       "legendFormat": "Per-process memory limit (in bytes); 0=unset"
      },
      {
       "expr": "sum(rate(haproxy_process_pool_allocated_bytes{instance=~\"$host\"}[$__rate_interval]))",
       "legendFormat": "Total amount of memory allocated in pools (in bytes)"
      },
      {
       "expr": "sum(rate(haproxy_process_pool_used_bytes{instance=~\"$host\"}[$__rate_interval]))",
       "legendFormat": "Total amount of memory used in pools (in bytes)"
      }
     ]
    },
    {
     "title": "Process - Tasks",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(haproxy_process_current_tasks{instance=~\"$host\"}[$__rate_interval]))",
       "legendFormat": "Current number of tasks"
      },
      {
       "expr": "sum(haproxy_process_current_run_queue{instance=~\"$host\"})",
       "legendFormat": "Current number of tasks in the run-queue"
      },
      {
       "expr": "sum(haproxy_process_stopping{instance=~\"$host\"})",
       "legendFormat": "Non zero means stopping in progress"
      }
     ]
    },
    {
     "title": "Process - Maximum open files / sockets",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(haproxy_process_max_fds{instance=~\"$host\"})",
       "legendFormat": "Maximum number of open file descriptors; 0=unset"
      },
      {
       "expr": "sum(haproxy_process_max_sockets{instance=~\"$host\"})",
       "legendFormat": "Maximum numer of open sockets"
      }
     ]
    },
    {
     "title": "Process - Jobs",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(haproxy_process_jobs{instance=~\"$host\"}[$__rate_interval]))",
       "legendFormat": "Current number of active jobs (listeners, sessions, open devices)"
      },
      {
       "expr": "sum(rate(haproxy_process_unstoppable_jobs{instance=~\"$host\"}[$__rate_interval]))",
       "legendFormat": "Current number of active jobs that can't be stopped during a soft stop"
      },
      {
       "expr": "sum(rate(haproxy_process_listeners{instance=~\"$host\"}[$__rate_interval]))",
       "legendFormat": "Current number of active listeners"
      }
     ]
    },
    {
     "title": "Process - Configured threads / processes",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(haproxy_process_nbthread{instance=~\"$host\"})",
       "legendFormat": "Threads"
      },
      {
       "expr": "sum(haproxy_process_nbproc{instance=~\"$host\"})",
       "legendFormat": "Processes"
      }
     ]
    },
    {
     "title": "Process - Idle",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg(haproxy_process_idle_time_percent{instance=~\"$host\"})",
       "legendFormat": "Idle to total ratio over last sample (percent)"
      }
     ]
    }
   ]
  }
 ]
}