{
 "title": "Network",
 "tags": [ "system" ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Host",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"}, instance)"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   },
   {
    "name": "device",
    "label": "Device",
    "query": {
     "query": "label_values(node_network_up{instance=\"$node\",job=\"$job\"}, device)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Last download rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(rate(node_network_receive_bytes_total{instance=\"$node\",job=\"$job\",device=~\"$device\"}[1m]))"
    }
   ]
  },
  {
   "title": "Total data downloaded",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(node_network_receive_bytes_total{instance=~\"$node\",device=~\"$device\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Last upload rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(rate(node_network_transmit_bytes_total{instance=\"$node\",job=\"$job\",device=~\"$device\"}[1m]))"
    }
   ]
  },
  {
   "title": "Total data uploaded",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(node_network_transmit_bytes_total{instance=~\"$node\",device=~\"$device\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Internet traffic per hour",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(node_network_receive_bytes_total{instance=~\"$node\",device=~\"$device\"}[60m])",
     "legendFormat": "{{device}}_receive"
    },
    {
     "expr": "increase(node_network_transmit_bytes_total{instance=~\"$node\",device=~\"$device\"}[60m])",
     "legendFormat": "{{device}}_transmit"
    }
   ]
  },
  { "title": "Network traffic on $device", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 }, "repeat": "device" },
  {
   "title": "Download $device",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=\"$node\",job=\"$job\",device=~\"$device\"}[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Upload $device",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=\"$node\",job=\"$job\",device=~\"$device\"}[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}