{
 "title": "NFS",
 "description": "NFS Prometheus Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(node_boot_time_seconds, job)"
   },
   {
    "name": "node",
    "label": "Host:",
    "query": "label_values(node_boot_time_seconds{job=~\"$job\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "NFS Requests by instance",
   "type": "timeseries",
   "description": "Request rate per 5m",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(node_nfs_requests_total{instance=~\"$node\", job=~\"$job\", proto=\"4\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "NFS Requests by method",
   "type": "timeseries",
   "description": "Request rate per 5m",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (method) (rate(node_nfs_requests_total{instance=~\"$node\", job=~\"$job\", proto=\"4\"}[5m]))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "NFS Mounts Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (node_filesystem_avail_bytes{instance=~\"$node\", job=\"$job\", fstype=\"nfs4\"} * 100 / node_filesystem_size_bytes{instance=~\"$node\", job=\"$job\", fstype=\"nfs4\"})",
     "legendFormat": "{{instance}} {{device}}"
    }
   ]
  },
  {
   "title": "NFS Mounts Errors",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_filesystem_device_error{instance=~\"$node\", job=\"$job\", fstype=\"nfs4\"}",
     "legendFormat": "{{instance}} {{device}}"
    }
   ]
  }
 ]
}