{
 "title": "Opcache",
 "tags": [
  "php-fpm",
  "opcache"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(opcache_exporter_build_info{job=\"opcache\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Opcache enabled",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(opcache_enabled{job=\"opcache\", instance=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Cache Size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(opcache_memory_usage_used_memory{job=\"opcache\", instance=~\"$host\"})",
     "legendFormat": "used memory"
    }
   ]
  },
  {
   "title": "Hits/Misses",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(opcache_statistics_hits{job=\"opcache\", instance=~\"$host\"})",
     "legendFormat": "hits"
    },
    {
     "expr": "sum(opcache_statistics_misses{job=\"opcache\", instance=~\"$host\"})",
     "legendFormat": "misses"
    }
   ]
  },
  {
   "title": "Cache full",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(opcache_cache_full{job=\"opcache\", instance=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Memory wasted",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(opcache_memory_usage_wasted_memory{job=\"opcache\", instance=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Hit rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(opcache_statistics_hit_rate{job=\"opcache\", instance=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Cached scripts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 9 },
   "targets": [
    {
     "expr": "sum(opcache_statistics_num_cached_scripts{job=\"opcache\", instance=~\"$host\"})",
     "legendFormat": "cached scripts"
    }
   ]
  },
  {
   "title": "Cached keys",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 9 },
   "targets": [
    {
     "expr": "sum(opcache_statistics_num_cached_keys{job=\"opcache\", instance=~\"$host\"})",
     "legendFormat": "cached keys"
    }
   ]
  }
 ]
}