{
 "title": "PHP-FPM",
 "description": "PHP-FPM aggregated data for multiple pools.",
 "tags": [ "php-fpm" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(php_fpm_accepted_connections_total, instance)"
    }
   },
   {
    "name": "pool",
    "label": "Pool",
    "query": {
     "query": "label_values(php_fpm_accepted_connections_total{instance=~\"$host\"}, socket_path)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(php_fpm_up{instance=~\"^$host\", socket_path=~\"$pool\"})",
     "legendFormat": "{{socket_path}}"
    }
   ]
  },
  {
   "title": "Pool Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 21, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (socket_path) (php_fpm_active_processes{instance=~\"^$host\", socket_path=~\"$pool\"}) / sum by (socket_path) ( php_fpm_max_active_processes{instance=~\"^$host\", socket_path=~\"$pool\"})",
     "legendFormat": "{{ socket_path }}"
    }
   ]
  },
  {
   "title": "Accepted Connections Rate",
   "type": "timeseries",
   "description": "Total number of accepted connections",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (socket_path) (rate(php_fpm_accepted_connections_total{instance=~\"^$host\", socket_path=~\"$pool\"} [$__rate_interval]))",
     "legendFormat": "{{socket_path}}"
    }
   ]
  },
  {
   "title": "Slow Requests Rate",
   "type": "timeseries",
   "description": "Number of requests that exceed request_slowlog_timeout",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (socket_path) (rate(php_fpm_slow_requests{instance=~\"^$host\", socket_path=~\"$pool\"} [$__rate_interval]))",
     "legendFormat": "{{ socket_path }} "
    }
   ]
  },
  {
   "title": "Active processes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(php_fpm_active_processes{instance=~\"^$host\", socket_path=~\"$pool\"}) by (socket_path )",
     "legendFormat": "{{ socket_path }} "
    }
   ]
  },
  {
   "title": "Max active processes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (socket_path) (php_fpm_max_active_processes{instance=~\"^$host\", socket_path=~\"$pool\"})",
     "legendFormat": "{{ socket_path }} "
    }
   ]
  },
  {
   "title": "Max children reached",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (socket_path) (php_fpm_max_children_reached{instance=~\"^$host\", socket_path=~\"$pool\"})",
     "legendFormat": "{{ socket_path }} "
    }
   ]
  },
  {
   "title": "Idle processes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (socket_path) (php_fpm_idle_processes{instance=~\"^$host\", socket_path=~\"$pool\"})",
     "legendFormat": "{{ socket_path }} "
    }
   ]
  }
 ]
}