{
 "title": "Plateform Overview",
 "tags": [ "system" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   },
   {
    "name": "host",
    "label": "Server",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"}, instance)"
    }
   },
   {
    "name": "mountpoints",
    "label": "Mountpoints",
    "query": {
     "query": "label_values(node_filesystem_avail_bytes{instance=~\"$host\"}, mountpoint)"
    }
   },
   {
    "name": "nic",
    "label": "Net Interface",
    "query": {
     "query": "label_values(node_network_up{instance=~\"$host\",job=\"$job\"}, device)"
    }
   },
   {
    "name": "production",
    "label": "Production",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(node_time_seconds{instance=~\"$host\",job=\"$job\"} - node_boot_time_seconds{instance=~\"$host\",job=\"$job\"})",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(100 - (avg(rate(node_cpu_seconds_total{instance=~\"$host\",mode=\"idle\"}[$__rate_interval])) * 100))",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(100 - ((node_memory_MemAvailable_bytes{instance=~\"$host\",job=\"$job\"} * 100) / node_memory_MemTotal_bytes{instance=~\"$host\",job=\"$job\"}))",
     "legendFormat": "Memory Usage"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_hwmon_temp_celsius{instance=~\"$host\",job=\"$job\"})",
     "legendFormat": "Temperature"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{instance=~\"$host\",job=\"$job\",device=~\"$nic\"}[1m]))",
     "legendFormat": "Current download"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(node_network_receive_bytes_total{instance=~\"$host\",device=~\"$nic\"}[$__range]))",
     "legendFormat": "Total download"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{instance=~\"$host\",job=\"$job\",device=~\"$nic\"}[1m]))",
     "legendFormat": "Current upload"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(node_network_transmit_bytes_total{instance=~\"$host\",device=~\"$nic\"}[$__range]))",
     "legendFormat": "Total upload"
    }
   ]
  },
  { "title": "Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "CPU & Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(100 - (avg(rate(node_cpu_seconds_total{instance=~\"$host\",mode=\"idle\"}[$__rate_interval])) * 100))",
     "legendFormat": "CPU usage"
    },
    {
     "expr": "avg(node_load5{instance=~\"$host\",job=\"$job\"})",
     "legendFormat": "Load Average"
    },
    {
     "expr": "avg(100 - ((node_memory_MemAvailable_bytes{instance=~\"$host\",job=\"$job\"} * 100) / node_memory_MemTotal_bytes{instance=~\"$host\",job=\"$job\"}))",
     "legendFormat": "Memory usage"
    }
   ]
  },
  {
   "title": "Internet traffic per hour",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(increase(node_network_receive_bytes_total{instance=~\"$host\",device=~\"$nic\"}[60m]))",
     "legendFormat": "receive"
    },
    {
     "expr": "sum(increase(node_network_transmit_bytes_total{instance=~\"$host\",device=~\"$nic\"}[60m]))",
     "legendFormat": "transmit"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{instance=~\"$host\",job=\"$job\"}[$__rate_interval])*8)",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{instance=~\"$host\",job=\"$job\"}[$__rate_interval])*8)",
     "legendFormat": "trans {{device}} "
    }
   ]
  },
  {
   "title": "Disk Space Used",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(100 - ((node_filesystem_avail_bytes{instance=~\"$host\",mountpoint=~\"$mountpoints\"} * 100) / node_filesystem_size_bytes{instance=~\"$host\",mountpoint=~\"$mountpoints\"})) by (mountpoint)",
     "legendFormat": "{{instance}} {{mountpoint}}"
    }
   ]
  },
  { "title": "Production", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "HAproxy responses rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(haproxy_frontend_http_responses_total{instance=~\"$production\"}[$__rate_interval])) by (code)",
     "legendFormat": "{{ code }}"
    }
   ]
  },
  {
   "title": "MySQL connections",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(max_over_time(mysql_global_status_threads_connected{instance=~\"$production\"}[$__rate_interval]) or mysql_global_status_threads_connected{instance=~\"$production\"})",
     "legendFormat": "Connections"
    }
   ]
  },
  {
   "title": "Cloudflare Requests / second",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(cloudflare_zone_requests_total{}[$__interval]))",
     "legendFormat": "total"
    },
    {
     "expr": "sum(rate(cloudflare_zone_requests_cached{}[$__interval]))",
     "legendFormat": "cached"
    }
   ]
  },
  {
   "title": "MySQL querries per second",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(rate(mysql_global_status_queries{instance=~\"$production\"}[$__rate_interval]) or irate(mysql_global_status_queries{instance=~\"$production\"}[5m]))",
     "legendFormat": "QPS"
    }
   ]
  }
 ]
}