{
 "title": "PostgreSQL",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "host", "label": "Host", "query": { "query": "label_values(pg_up, instance)" } }
  ]
 },
 "panels": [
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (short_version) (pg_static{instance=~\"$host\"})",
     "legendFormat": "{{short_version}}"
    }
   ]
  },
  {
   "title": "Shared Buffers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_settings_shared_buffers_bytes{instance=~\"$host\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Effective Cache",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_settings_effective_cache_size_bytes{instance=~\"$host\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maintenance Work Mem",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_settings_maintenance_work_mem_bytes{instance=~\"$host\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max WAL Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_settings_max_wal_size_bytes{instance=~\"$host\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Worker Processes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_settings_max_worker_processes{instance=~\"$host\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Parallel Workers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_settings_max_parallel_workers{instance=~\"$host\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Connections",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_settings_max_connections{instance=~\"$host\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transactions rate (5m)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "sum by(instance) (rate(pg_stat_database_xact_commit{instance=~\"$host\"}[$__rate_interval]))",
     "legendFormat": "{{instance}} commits"
    },
    {
     "expr": "sum by(instance) (rate(pg_stat_database_xact_commit{instance=~\"$host\"}[$__rate_interval]))",
     "legendFormat": "{{instance}} rollbacks"
    }
   ]
  },
  {
   "title": "Lock tables rate (5m)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "expr": "sum by(instance) (rate(pg_locks_count{instance=~\"$host\"}[$__rate_interval]))",
     "legendFormat": "{{instance}} locks"
    }
   ]
  },
  {
   "title": "Activity rate (5m)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum by(instance) (rate(pg_stat_activity_count{instance=~\"$host\", state=\"active\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Idle conn rate (5m)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "sum by(instance) (rate(pg_stat_activity_count{instance=~\"$host\", state=~\"idle|idle in transaction|idle in transaction (aborted)\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "SELECT data rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(pg_stat_database_tup_fetched{instance=~\"$host\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Return data rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(pg_stat_database_tup_returned{instance=~\"$host\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}