{
 "title": "Varnish",
 "description": "A dashboard to use to debug a running varnish instance. Easily track requests, cache hits, network i/o, sessions, threads, bans, ban lurker and the ban list size",
 "tags": [ "varnish" ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(varnish_up, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "cluster",
   "targets": [
    {}
   ]
  },
  {
   "title": "Frontend Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(varnish_main_client_req{instance=~\"^($host).*\"}[5m]))"
    }
   ]
  },
  {
   "title": "Backend Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(varnish_main_backend_req{instance=~\"^$host.*\"}[5m]))"
    }
   ]
  },
  {
   "title": "Loaded VMODs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(varnish_main_vmods{instance=~\"^($host).*\"})"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(varnish_main_uptime{instance=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Cache Hit Rate",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(( rate(varnish_main_cache_hit{instance=~\"^($host).*\"}[5m]) / rate(varnish_main_client_req{instance=~\"^($host).*\"}[5m]) ))"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(varnish_main_client_req{instance=~\"^($host).*\"}[5m]))",
     "legendFormat": "frontend"
    },
    {
     "expr": "sum(irate(varnish_main_backend_req{instance=~\"^($host).*\"}[5m]))",
     "legendFormat": "backend"
    },
    {
     "expr": "sum(varnish_main_fetch_total{instance=~\"^($host).*\"})",
     "legendFormat": "fetch total"
    },
    {
     "expr": "sum(irate(varnish_main_fetch_total{instance=~\"^($host).*\"}[5m]))",
     "legendFormat": "fetched objects"
    }
   ]
  },
  {
   "title": "Cache hits",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(rate(varnish_main_cache_hit{instance=~\"^($host).*\"}[5m]) / rate(varnish_main_client_req{instance=~\"^($host).*\"}[5m]))",
     "legendFormat": "cache hit %"
    },
    {
     "expr": "avg(1 - (rate(varnish_main_cache_hit{instance=~\"^($host).*\"}[5m]) / rate(varnish_main_client_req{instance=~\"^($host).*\"}[5m])))",
     "legendFormat": "cache miss %"
    },
    {
     "expr": "avg(1 - (rate(varnish_main_cache_hitpass{instance=~\"^($host).*\"}[5m]) / rate(varnish_main_client_req{instance=~\"^($host).*\"}[5m])))",
     "legendFormat": "cache hit pass %"
    }
   ]
  },
  {
   "title": "Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(irate(varnish_main_s_resp_hdrbytes{instance=~\"^($host).*\"}[5m]) + irate(varnish_main_s_resp_bodybytes{instance=~\"^($host).*\"}[5m]))",
     "legendFormat": "frontend"
    },
    {
     "expr": "sum(irate(varnish_backend_beresp_hdrbytes{instance=~\"^($host).*\"}[5m]) + irate(varnish_backend_beresp_bodybytes{instance=~\"^($host).*\"}[5m]))",
     "legendFormat": "backend"
    }
   ]
  },
  {
   "title": "Cache",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(varnish_sma_g_bytes{instance=~\"$host\"})",
     "legendFormat": "cache"
    }
   ]
  },
  {
   "title": "New row",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Backend Connections (per minute)",
   "type": "timeseries",
   "gridPos": { "h": 20, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(varnish_main_backend_conn{instance=~\"^($host).*\"}[1m]))",
     "legendFormat": "Backend conn. success"
    },
    {
     "expr": "sum(rate(varnish_main_backend_recycle{instance=~\"^($host).*\"}[1m]))",
     "legendFormat": "Backend conn. recycles"
    },
    {
     "expr": "sum(rate(varnish_main_backend_reuse{instance=~\"^($host).*\"}[1m]))",
     "legendFormat": "Backend conn. reuses"
    },
    {
     "expr": "sum(rate(varnish_main_backend_fail{instance=~\"^($host).*\"}[1m]))",
     "legendFormat": "Backend conn. failures"
    },
    {
     "expr": "sum(rate(varnish_main_backend_unhealthy{instance=~\"^($host).*\"}[1m]))",
     "legendFormat": "Backend conn. not attempted"
    },
    {
     "expr": "sum(rate(varnish_main_backend_busy{instance=~\"^($host).*\"}[1m]))",
     "legendFormat": "Backend conn. too many"
    },
    {
     "expr": "sum(rate(varnish_main_backend_req{instance=~\"^($host).*\"}[1m]))",
     "legendFormat": "Backend requests made"
    },
    {
     "expr": "sum(rate(varnish_main_backend_retry{instance=~\"^($host).*\"}[1m]))",
     "legendFormat": "Backend conn. retry"
    },
    {
     "expr": "sum(rate(varnish_backend_conn{instance=~\"^($host).*\"}[1m]))",
     "legendFormat": "Concurrent connections to backend"
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "timeseries",
   "gridPos": { "h": 20, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(type) (rate(varnish_main_sessions{instance=~\"^($host).*\"}[1m]))",
     "legendFormat": "session - {{type}}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(varnish_main_threads_created{instance=~\"^($host).*\"})",
     "legendFormat": "Threads created"
    },
    {
     "expr": "sum(varnish_main_threads_destroyed{instance=~\"^($host).*\"})",
     "legendFormat": "Threads destroyed"
    },
    {
     "expr": "sum(varnish_main_threads_failed{instance=~\"^($host).*\"})",
     "legendFormat": "Thread creation failed"
    },
    {
     "expr": "sum(varnish_main_threads_limited{instance=~\"^($host).*\"})",
     "legendFormat": "Max Threads hit"
    },
    {
     "expr": "sum(varnish_main_threads{instance=~\"^($host).*\"})",
     "legendFormat": "Total number of threads"
    },
    {
     "expr": "sum(varnish_main_thread_queue_len{instance=~\"^($host).*\"})",
     "legendFormat": "Length of session queue waiting for threads"
    },
    {
     "expr": "sum(varnish_main_pools{instance=~\"^($host).*\"})",
     "legendFormat": "Number of thread pools   "
    }
   ]
  }
 ]
}