---
- name: 'cloudflare exporter | check vars are defined'
  assert:
    that:
      - cloudflare_api_key is defined
      - cloudflare_api_email is defined
  tags: ['prometheus_cloudflare']

- include_tasks: ../docker.yml
  tags: ['prometheus_cloudflare']
