---
- include_tasks: ../common.yml
  tags: ['prometheus_postgres_exporter']

- name: 'postgres exporter | configuration'
  template:
    src: conf/prometheus-postgres-exporter.j2
    dest: /etc/default/prometheus-postgres-exporter
    owner: root
    group: root
    mode: 0600
  register: prometheus_postgres_exporter_configuration
  notify:
    - 'postgres-exporter-restart'
  tags: ['prometheus_postgres_exporter']
